patchedDependencies:
  '@vite-hub/rate-limit@0.0.1': patches/@vite-hub__rate-limit@0.0.1.patch
  '@vite-hub/schedule@0.0.1': patches/@vite-hub__schedule@0.0.1.patch
  vite-hub@0.0.1: patches/vite-hub@0.0.1.patch
supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc
  os:
    - current
    - linux
